#!/bin/bash

time=$(date +%H:%M)

read -p "Enter command: " command

while [ -z $command ]
do
	read -p "Please enter a command: " command
done

read -p "Enter time (HH:MM) to notify yourself: " alarm

until [[ "$alarm" =~ [0-9][0-9]\:[0-9][0-9] ]]
do
	read -p "Please enter a valid time: " alarm
done

until [ $time = $alarm ]
do
	time=$(date +%H:%M)
done

echo "Execute $command"



