#!/bin/bash


read -p "Enter user: " user

cat /etc/passwd |cut -d ":" -f1 |grep -w $user &> /dev/null

if [ $? -eq 0 ]
then
	who |awk '{print $1}' |grep -w $user &> /dev/null
	until [ $? -eq 0 ]
	do
		echo "Not logged in yet" ; sleep 1
		who |awk '{print $1}' |grep -w $user &> /dev/null
	done
	echo "The user is logged in"
else

	echo "User does not exists"
fi
