#!/bin/bash 

read -p "Please enter your user name: " name

cat /etc/passwd |cut -d ":" -f1 |grep -w $name &> /dev/null

if [ $? -eq 0 ]
then
	uid=$(id -u $name)
	if [ $uid -ge 500 -a $uid -le 1000 ]
	then
		id $name ; cat /etc/passwd |grep $name
	else
	echo "The UID of $name is not between 500 to 1000"
	sleep 5
	kill -9 $PPID
	fi
else
	echo "User not found"
fi
